### ISSUE TITLE
GUI - Start Masternodes Button(s) Not Working

### ISSUE THREAD

**Issue by YuurinBee** [ZENZO-Ecosystem/ZENZO-Core-Archive#15]
**Describe the bug**
Under the Masternodes Tab in the ZENZO Core Wallet, the buttons "Start alias", "Start all", "Start MISSING" do not work. At times they have started the masternode, but for some reason it does not stay up. The best console command that works from my experience is ```startmasternode alias false masternodename```. If there would be a way to link this command with the appropriate buttons, I believe it would resolve the issue. 

**To Reproduce**
1. Go to 'Masternodes Tab'
2. Click on ```Start alias```, ```Start all```, ```Start MISSING```
3. Test to see if it enables the masternodes on the network, not just on the GUI. 
4. Go to your VPS and type the command ```zenzo/zenzo-cli masternode status```.
5. If ```Status: 4```, the masternode is running correctly. If not, issue is unresolved. 

**Expected behavior**
3 Masternode Buttons to function properly
1. ```Start alias``` starts the respective masternode and put it's online
2. ```Start all``` starts all masternodes and puts them online
3. ```Start MISSING``` starts MISSING masternodes and puts them online

**Screenshots**
![Error-Screenshot](https://i.imgur.com/JBRcMva.png)

**Desktop (please complete the following information):**
 - OS: [Mac Mojave]
 - Browser [n/a]
 - Version [v1.0.0 & v1.2.0]

**Comment by JSKitty** [comment]
Tested by multiple community members and team, all have been successful. Closing issue.
